### ISSUE TITLE
Added selected state to popover items

### ISSUE THREAD

**Issue by nickzafiropulos** [nearform/quantum#211]
https://www.figma.com/file/XFbhstkgQFz8ZefAU3w2p4/1.-Quantum-Design-System?type=design&node-id=360-11193&mode=design

**Comment by andreaforni** [comment]
Hi @nickzafiropulos,
based on what we said here in the [#270 issue](https://github.com/nearform/quantum/issues/270#issuecomment-1886659044), popover items does not exist in the library. The developers are free to add whatever they want to the popover content. 

For this reason, I think we should close this ticket.

**Comment by nickzafiropulos** [comment]
I have left a comment on #270 - If possible, I'd like to revisit the ticket to improve it, once #278 has been implemented

**Comment by marceloFerreira90** [comment]
Issue resolved in 270
