### ISSUE TITLE
[Design Update] - New brand

### ISSUE THREAD

**Issue by simoneb** [nearform/quantum#231]
All the styles should reflect the new brand.

**Comment by nickzafiropulos** [comment]
We will be waiting for the final brand colour palette to be released, and also for the new website to be launched, so that we can approach this with a more informed and accurate direction.

Expecting to have more clarification Mid Jan.

**Comment by simoneb** [comment]
@nickzafiropulos @Filippoperl here are the new branding guidelines and assets. I think they are still not open to everybody but they will be at some point. https://www.notion.so/nearform/64c2388f531c41d495c8e7fb9d4822c2?v=fe4fcea79dea4a83bb6eb29cc3cf4435

**Comment by nickzafiropulos** [comment]
> @nickzafiropulos @Filippoperl here are the new branding guidelines and assets. I think they are still not open to everybody but they will be at some point. https://www.notion.so/nearform/64c2388f531c41d495c8e7fb9d4822c2?v=fe4fcea79dea4a83bb6eb29cc3cf4435

I have no access to that in Notion at the moment unfortunately 
@Filippoperl when we do have access and you're ready to work on the rebranding I'm happy to have a call to discuss what I was thinking in terms of which colour variables need changing in the DS (although my availability is limited this week and I'm in workshops)

**Comment by Filippoperl** [comment]
@Filippoperl and @mattobee will check new brand guidelines and understand what needs to be normalised in Quantum DS

**Comment by simoneb** [comment]
@hizo @luke88jones @marceloFerreira90 @Filippoperl here's the revised plan for implementing the changes for the new brand.

In terms of responsibilitie and splitting of work:

- @hizo will take care of checking with @Filippoperl what changes need to be done. @Filippoperl's earlier work on this is captured in https://github.com/nearform/quantum/issues/186
- @hizo will implement the changes in quantum
- once we have the changes in quantum and a new version of the package:
  - @hizo will include those changes to skills-matrix
  - @luke88jones will include those changes in the profiles app
  - the two activities above should largely boil down to bumping the package and ensuring consistency
- @marceloFerreira90 can support as he previously worked on both profiles and quantum
- @Filippoperl can support (please consider he's now busy on a propject kickoff) as the designer who looked into the digital product implementation of the new brand guidelines
