### ISSUE TITLE
[Component] - Radio group

### ISSUE THREAD

**Issue by nickzafiropulos** [nearform/quantum#263]
Figma - https://www.figma.com/file/XFbhstkgQFz8ZefAU3w2p4/1.-Quantum-Design-System?type=design&node-id=67-737&mode=design

Storybook - https://nearform.github.io/quantum/?path=/docs/form-radiogroup--docs

1.  There is too little spacing between the radio button and the label. Please ensure there is 8px spacing here.
2. The vertical alignment looks slightly off (label looks 1-2px too low). Please ensure the radio button and the label line up vertically
3. Check the spacing between each row. There should be 12 px

**Comment by andreaforni** [comment]
Hi @marceloFerreira90,
I think we need a better handling of the labels. At the moment, Quantum provides a `Label` component and many different form components, like `Switch`, `Radio`, and `Checkbox`. 
If you want to add a label to these fields, you have to do it manually: 
- you have to create a `div` container, adding some Tailwind CSS classes, like `flex`, horizontal and vertical spacing, etc...
- add to this `div` the `Label` and `Switch`/`Radio`/`Checkbox` components

This is what happens now in the `Radio` or `Switch` storybooks. We create "demo" components that add labels to those input elements. 
Let us avoid reinventing the wheel every time and provide a better handling of input labels.
I checked some of the existing UI toolkits:
- NetxUI: set the label as a child of the input component: `<Radio value="buenos-aires">Buenos Aires</Radio>` [[link](https://nextui.org/docs/components/radio-group)]
- Blueprint: use a label prop: ` <Radio label="Salad" value="two" />` [[link](https://blueprintjs.com/docs/#core/components/radio)]
- MUI: use a wrapper component `<FormControlLabel value="male" control={<Radio />} label="Male" />` [[link](https://mui.com/material-ui/react-radio-button/)]

Of the three options, I think the best is the MUI one for 2 reasons:
- Label and input are separated. You can use a `<Radio>` without a label.
- We do not pollute the input properties if we want to customize the label, for example, by adding a "hint" text or a label position.

So, my idea is to:
- keep the keep the `Label` and input components independent
- provide a new component called "ControlLabel": `<ControlLabel label="Male"><Radio value="male" /></ControlLabel>`

What do you think?

**Comment by andreaforni** [comment]
> Hi @marceloFerreira90, I think we need a better handling of the labels. At the moment, Quantum provides a `Label` component and many different form components, like `Switch`, `Radio`, and `Checkbox`. If you want to add a label to these fields, you have to do it manually:
> 
> * you have to create a `div` container, adding some Tailwind CSS classes, like `flex`, horizontal and vertical spacing, etc...
> * add to this `div` the `Label` and `Switch`/`Radio`/`Checkbox` components
> 
> This is what happens now in the `Radio` or `Switch` storybooks. We create "demo" components that add labels to those input elements. Let us avoid reinventing the wheel every time and provide a better handling of input labels. I checked some of the existing UI toolkits:
> 
> * NetxUI: set the label as a child of the input component: `<Radio value="buenos-aires">Buenos Aires</Radio>` [[link](https://nextui.org/docs/components/radio-group)]
> * Blueprint: use a label prop: ` <Radio label="Salad" value="two" />` [[link](https://blueprintjs.com/docs/#core/components/radio)]
> * MUI: use a wrapper component `<FormControlLabel value="male" control={<Radio />} label="Male" />` [[link](https://mui.com/material-ui/react-radio-button/)]
> 
> Of the three options, I think the best is the MUI one for 2 reasons:
> 
> * Label and input are separated. You can use a `<Radio>` without a label.
> * We do not pollute the input properties if we want to customize the label, for example, by adding a "hint" text or a label position.
> 
> So, my idea is to:
> 
> * keep the keep the `Label` and input components independent
> * provide a new component called "ControlLabel": `<ControlLabel label="Male"><Radio value="male" /></ControlLabel>`
> 
> What do you think?

I created a new ticket to capture this requirement: #293
