### ISSUE TITLE
Leave tooltip exposed for 0.5 second after mouse leave.

### ISSUE THREAD

**Issue by nstolpe** [nearform/quantum#277]
This is a follow up to [267](https://github.com/nearform/quantum/issues/267), addressing the second issue mentioned there:

> 2. Can we leave the tooltip exposed for a little longer when the mouse leaves the element? It should be 0.5 seconds.

I was unable to figure out how to enable this delay, but I have an [issue open on readix-ui's discussion board.](https://github.com/radix-ui/primitives/discussions/2633). If someone replies with a solution there we sohuld be able to close this out.

**Comment by nstolpe** [comment]
A maintainer responded to me, and it looks like this isn't possible.

**Comment by simoneb** [comment]
Ok cool, thanks. Closing this then
