### ISSUE TITLE
Replace custom icons with a third-party library

### ISSUE THREAD

**Issue by andreaforni** [nearform/quantum#297]
We are providing 15 custom icons: [https://nearform.github.io/quantum/?path=/docs/icons--docs](https://nearform.github.io/quantum/?path=/docs/icons--docs)

These icons are only used in the Storybook examples, so I think it's better to replace them with a third-party library because:
1. We are not developing an icon toolkit
2. It reduces the work of the dev

The Figma designs use [Flowbite icons](https://flowbite.com/icons/), so I think this is a good candidate.

**Comment by marceloFerreira90** [comment]
as we are using the  flowbite icons from figma and tailwind  we can use their npm information 
https://github.com/themesberg/flowbite-icons
https://flowbite-svelte.com/docs/extend/icons
https://www.npmjs.com/package/flowbite

**Comment by andreaforni** [comment]
After an internal discussion, we decided to use [Bootstrap Icons](https://icons.getbootstrap.com/) because they can be easily integrated in Figma.
